import { appAlert, editorValues, expect, hydrated, markWindow, stillSameDocument, test } from './fixtures'

test.use({ colorScheme: 'light' })

test('starts in English and exposes a keyboard-operated language selector', async ({ page }) => {
  await page.goto('./')
  await hydrated(page)
  const selector = page.getByRole('combobox', { name: 'Interface language' })
  await expect(selector).toHaveValue('en')
  await expect(page.locator('html')).toHaveAttribute('lang', 'en')
  await expect(page.locator('html')).toHaveAttribute('dir', 'ltr')
  await expect(selector.getByRole('option')).toHaveText(['English', 'العربية'])

  await selector.focus()
  await expect(selector).toBeFocused()
  await page.keyboard.press('End')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('combobox', { name: 'لغة الواجهة' })).toHaveValue('ar')
  await expect(page.getByRole('navigation', { name: 'التنقل الرئيسي' }).getByRole('link', { name: 'تعلّم' })).toBeVisible()
  expect(await page.getByRole('banner').getByRole('combobox').evaluate((element) => {
    const style = getComputedStyle(element)
    return style.outlineStyle !== 'none' && parseFloat(style.outlineWidth) > 0
  })).toBe(true)
})

test('switching preserves the URL, populated tool inputs, saved work, progress and theme', async ({ page }) => {
  await page.goto('learn/linear-systems/')
  await page.getByRole('button', { name: 'Mark lesson complete' }).click()
  await page.getByRole('button', { name: 'Switch to dark theme' }).click()
  await page.goto('tools/rref/?example=two-by-two#main')
  await expect(page.locator('#rref-2-0')).toHaveCount(0)
  await page.locator('#rref-0-0').fill('7/2')
  await page.getByText('Save and share', { exact: true }).click()
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  const cells = await editorValues(page, 'rref', 2, 3)
  const preserved = await page.evaluate(() => Object.fromEntries(
    Object.entries(localStorage).filter(([key]) => key.startsWith('linearlab:') && key !== 'linearlab:language'),
  ))
  expect(preserved['linearlab:theme']).toBe('dark')
  expect(JSON.parse(preserved['linearlab:progress:v1'] as string).completed).toContain('sys-intro')
  expect(JSON.parse(preserved['linearlab:workspace:rref:v1'] as string).cells).toEqual(cells)
  const originalUrl = page.url()
  await markWindow(page)

  await page.getByRole('banner').getByRole('combobox').selectOption('ar')
  await expect(page).toHaveURL(originalUrl)
  expect(await stillSameDocument(page)).toBe(true)
  await expect(page.locator('html')).toHaveAttribute('lang', 'ar')
  await expect(page.locator('html')).toHaveAttribute('dir', 'rtl')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('حل أنظمة المعادلات')
  await expect(page).toHaveTitle('حل أنظمة المعادلات · LinearLab')
  expect(await editorValues(page, 'rref', 2, 3)).toEqual(cells)
  await expect(page.getByText('تم الحفظ في هذا المتصفح', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => Object.fromEntries(
    Object.entries(localStorage).filter(([key]) => key.startsWith('linearlab:') && key !== 'linearlab:language'),
  ))).toEqual(preserved)

  await page.getByRole('navigation', { name: 'التنقل الرئيسي' }).getByRole('link', { name: 'تدرّب' }).click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('تدرّب على اختزال الصفوف')
  await expect(page).toHaveTitle('التدريب · LinearLab')
  await expect(page.getByRole('banner').getByRole('combobox')).toHaveValue('ar')
  await page.goBack()
  await expect(page.locator('#rref-0-0')).toHaveValue('7/2')
  await page.reload()
  await expect(page.getByRole('banner').getByRole('combobox')).toHaveValue('ar')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.getByText('الحفظ والمشاركة', { exact: true }).click()
  await page.getByRole('button', { name: 'استعادة', exact: true }).click()
  expect(await editorValues(page, 'rref', 2, 3)).toEqual(cells)
  expect(await page.evaluate(() => localStorage.getItem('linearlab:progress:v1'))).toBe(preserved['linearlab:progress:v1'])
})

test('English course text and mathematical tables remain LTR in the Arabic interface', async ({ page }) => {
  await page.goto('learn/gauss-jordan-elimination/#one-pivot-at-a-time')
  await page.getByRole('banner').getByRole('combobox').selectOption('ar')
  const title = page.getByRole('heading', { level: 1 })
  await expect(title).toContainText('Gauss–Jordan elimination')
  await expect(title).toHaveAttribute('lang', 'en')
  await expect(title).toHaveAttribute('dir', 'ltr')
  const formula = page.locator('main .katex').filter({ visible: true }).first()
  await expect(formula).toBeVisible()
  expect(await formula.evaluate((element) => {
    const content = element.closest('[lang="en"][dir="ltr"]')
    return Boolean(content) && getComputedStyle(element).direction === 'ltr'
  })).toBe(true)
  await expect(page.getByRole('button', { name: 'تحقق من الإجابة' })).toBeVisible()

  await page.goto('practice/needs-a-swap/')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Start with a swap')
  const matrix = page.getByRole('table', { name: 'المصفوفة الحالية' })
  await expect(matrix).toBeVisible()
  expect(await matrix.evaluate((element) => getComputedStyle(element).direction)).toBe('ltr')
  await page.getByRole('button', { name: 'اطلب تلميحًا' }).click()
  const hint = page.getByText('Focus on column 1: its pivot belongs in row 1.')
  await expect(hint).toBeVisible()
  expect(await hint.evaluate((element) => Boolean(element.closest('[lang="en"][dir="ltr"]')))).toBe(true)
})

test('existing validation updates language without losing the invalid input', async ({ page }) => {
  await page.goto('tools/rref/?example=two-by-two')
  await page.locator('#rref-1-1').fill('abc')
  await page.getByRole('button', { name: 'Solve step by step' }).click()
  await expect(appAlert(page)).toContainText('is not a number')
  await page.getByRole('banner').getByRole('combobox').selectOption('ar')
  await expect(appAlert(page)).toContainText('صحّح قيمة واحدة للمتابعة')
  await expect(appAlert(page)).toContainText('ليست عددًا')
  await expect(page.locator('#rref-1-1')).toHaveValue('abc')
  await expect(page.locator('#rref-1-1')).toHaveAttribute('aria-invalid', 'true')
  await expect(page.locator('#rref-1-1')).toHaveAttribute('dir', 'ltr')
})

test('a selected language survives client navigation when browser storage is denied', async ({ page }) => {
  await page.addInitScript(() => {
    Object.defineProperty(window, 'localStorage', { get() { throw new DOMException('Storage denied', 'SecurityError') } })
  })
  await page.goto('./')
  await hydrated(page)
  await page.getByRole('banner').getByRole('combobox').selectOption('ar')
  await markWindow(page)
  await page.getByRole('navigation', { name: 'التنقل الرئيسي' }).getByRole('link', { name: 'تدرّب' }).click()
  await expect(page).toHaveURL(/\/practice\/$/)
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('تدرّب على اختزال الصفوف')
  await expect(page.getByRole('banner').getByRole('combobox')).toHaveValue('ar')
  await expect(page.locator('html')).toHaveAttribute('dir', 'rtl')
  expect(await stillSameDocument(page)).toBe(true)
})

test('switching preserves both populated matrices, the scalar, saved work and multiplication position', async ({ page }) => {
  await page.goto('tools/matrices/')
  await page.locator('#mA-0-0').fill('7/2')
  await page.locator('#mB-0-0').fill('-9/2')
  await page.getByLabel('Scalar k').fill('3/4')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  const saved = await page.evaluate(() => localStorage.getItem('linearlab:workspace:matrices:v1'))
  const a = await editorValues(page, 'mA', 2, 2)
  const b = await editorValues(page, 'mB', 2, 2)
  await page.getByRole('button', { name: /A × B/ }).click()
  const englishControls = page.getByRole('group', { name: 'Multiplication controls' })
  await englishControls.getByRole('button', { name: 'Next product' }).click()
  await englishControls.getByRole('button', { name: 'Next product' }).click()
  await expect(englishControls.locator('p')).toHaveText('Product 2 of 8')
  await expect(page.getByRole('table', { name: 'Product C = AB' }).getByText('?', { exact: true })).toHaveCount(3)

  await page.getByRole('banner').getByRole('combobox').selectOption('ar')
  expect(await editorValues(page, 'mA', 2, 2)).toEqual(a)
  expect(await editorValues(page, 'mB', 2, 2)).toEqual(b)
  await expect(page.getByLabel('العدد k')).toHaveValue('3/4')
  expect(await page.evaluate(() => localStorage.getItem('linearlab:workspace:matrices:v1'))).toBe(saved)
  const controls = page.getByRole('group', { name: 'أزرار عرض الضرب' })
  await expect(controls.locator('p')).toHaveText(/حاصل الضرب.*2.*من.*8/)
  const product = page.getByRole('table', { name: /ناتج الضرب.*C = AB/ })
  await expect(product.getByText('?', { exact: true })).toHaveCount(3)
  expect(await product.evaluate((element) => getComputedStyle(element).direction)).toBe('ltr')
  await page.getByRole('button', { name: 'عرض النتيجة النهائية' }).click()
  await expect(product.getByText('?', { exact: true })).toHaveCount(0)
})
