import { MatrixView } from '@/components/matrix/MatrixView'
import { explainStep } from '@/lib/math/explain'
import { solutionLines } from '@/lib/math/notation'
import type { SystemAnalysis } from '@/lib/math/solve'
import { variableList } from '@/lib/export'
import styles from './rref.module.css'

/** Every step on one page. Hidden on screen; shown when printing. */
export function SolutionReport({ analysis }: { analysis: SystemAnalysis }) {
  const n = analysis.variables
  const labels = [...variableList(n), 'b']
  return (
    <section className={`print-only ${styles.report}`}>
      <h1>Gauss–Jordan solution</h1>
      <p>
        {analysis.equations} equations, {n} variables. Generated by LinearLab with exact fractions.
      </p>
      <MatrixView matrix={analysis.elimination.input} label="Starting matrix" augmentAt={n} columnLabels={labels} size="sm" caption="Starting matrix [A | b]" />
      <ol className={styles.reportSteps}>
        {analysis.elimination.steps.map((step) => {
          const e = explainStep(step, { kind: 'system' })
          return (
            <li key={step.number}>
              <p>
                <strong>
                  Step {step.number}: {e.operation}
                </strong>{' '}
                {e.reason}
              </p>
              <MatrixView matrix={step.after} label={`After step ${step.number}`} augmentAt={n} size="sm" />
            </li>
          )
        })}
      </ol>
      <h2>Result</h2>
      <ul>
        {solutionLines(analysis.solution).map((line) => (
          <li key={line}>{line}</li>
        ))}
      </ul>
    </section>
  )
}
